import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://cdn.jsdelivr.net/gh/Orphe-OSS/ORPHE-CORE.js/js/ORPHE-CORE.js"
          crossOrigin="anonymous"
          type="text/javascript"
        />
        <script
          src="https://cdn.jsdelivr.net/gh/Orphe-OSS/ORPHE-CORE.js/js/CoreToolkit.js"
          crossOrigin="anonymous"
          type="text/javascript"
        />
      </head>
      <body>
        <header>
          <h1>Orphe proto</h1>
        </header>
        <main className={inter.className}>{children}</main>
      </body>
    </html>
  );
}
